# Generated by Django 5.0.6 on 2024-07-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_exercise_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Load',
        ),
        migrations.DeleteModel(
            name='Reps',
        ),
        migrations.DeleteModel(
            name='Sets',
        ),
    ]
